dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

services: mysql

before_install:
  - mysql -e 'CREATE DATABASE blog_test;'

install:
  - composer install

script: vendor/bin/phpunit --env=travis